os:
  - Visual Studio 2015
pull_requests:
 do_not_increment_build_number: true
skip_tags: true
skip_commits:
  message: /(Created|Update).*\.(png|jpg|jpeg|bmp|gif|md)/
skip_branch_with_pr: true
environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
      BITS: 32
      FEATURES: default
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64
      FEATURES: default
    - TARGET: i686-pc-windows-msvc
      BITS: 32
      FEATURES: rust-native-tls
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64
      FEATURES: rust-native-tls
install:
  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-toolchain=stable-%TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose %cargoflags%