[package]
name = "holidayapi"
version = "0.0.1"
authors = ["Guilherme Branco Stracini <guilherme@guilhermebranco.com.br>"]
description = "The Holiday API client wrapper written in Rust."
repository = "https://github.com/guibranco/holiday-api-rust.git"
homepage = "https://github.com/guibranco/holiday-api-rust"
keywords = ["rest", "client", "json", "hyper", "holiday", "holiday-api"]
categories = ["network-programming", "web-programming::http-client"]
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "github-rs/github-rs", branch = "master" }
appveyor = { repository = "github-rs/github-rs", branch = "master", service = "github" }

[dependencies]
hyper = "0.12.27"
hyper-rustls = { version = "0.16.1", optional = true }
hyper-tls = { version = "0.3.2", optional = true }
native-tls = { version = "0.2.2", optional = true }
error-chain = "0.12.0"
tokio-core = "0.1.17"
futures = "0.1.26"
serde = "1.0.90"
serde_json = "1.0.39"

[dev-dependencies]
serde_derive = "1.0.90"